/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoqRouteImport } from './routes/boq'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as SiteRouteImport } from './routes/site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqRoute = BoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boq': typeof BoqRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/letter': typeof LetterRoute
  '/site': typeof SiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boq': typeof BoqRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/letter': typeof LetterRoute
  '/site': typeof SiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boq': typeof BoqRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/letter': typeof LetterRoute
  '/site': typeof SiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boq' | '/catalog' | '/compare' | '/letter' | '/site'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boq' | '/catalog' | '/compare' | '/letter' | '/site'
  id: '__root__' | '/' | '/boq' | '/catalog' | '/compare' | '/letter' | '/site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoqRoute: typeof BoqRoute
  CatalogRoute: typeof CatalogRoute
  CompareRoute: typeof CompareRoute
  LetterRoute: typeof LetterRoute
  SiteRoute: typeof SiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq': {
      id: '/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof BoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoqRoute: BoqRoute,
  CatalogRoute: CatalogRoute,
  CompareRoute: CompareRoute,
  LetterRoute: LetterRoute,
  SiteRoute: SiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
